Repository dataprev/ideax, pull requests merged in 2018-10, with the labels that each got.

#59 Feature/test support
  .gitignore
  Dockerfile
  Makefile
  conftest.py
  dev/Dockerfile
  docker-dev.yml
  docker-entrypoint.sh
  docker/requirements.txt
  ideax/models.py
  ideax/pytest/__init__.py
  ideax/pytest/fixtures.py
  ideax/settings_test.py
  ideax/tests/snapshots/__init__.py
  ideax/tests/snapshots/snap_test_category_form.py
  ideax/tests/test_base.py
  ideax/tests/test_category.py
  ideax/tests/test_category_form.py
  ideax/tests/test_views.py
  pytest.ini
  requirements.txt
  requirements/_test.txt
Labels: enhancement

#74 More tests
  Makefile
  ideax/models.py
  ideax/pytest/fixtures.py
  ideax/settings/apps/_martor.py
  ideax/settings/django/_core.py
  ideax/tests/__init__.py
  ideax/tests/forms/__init__.py
  ideax/tests/forms/snapshots/__init__.py
  ideax/tests/forms/snapshots/snap_test_category.py
  ideax/tests/forms/snapshots/snap_test_category_image.py
  ideax/tests/forms/snapshots/snap_test_challenge.py
  ideax/tests/forms/snapshots/snap_test_criterion.py
  ideax/tests/forms/snapshots/snap_test_idea.py
  ideax/tests/forms/snapshots/snap_test_idea_update.py
  ideax/tests/forms/snapshots/snap_test_use_term.py
  ideax/tests/forms/test_category.py
  ideax/tests/forms/test_category_image.py
  ideax/tests/forms/test_challenge.py
  ideax/tests/forms/test_criterion.py
  ideax/tests/forms/test_evaluation.py
  ideax/tests/forms/test_idea.py
  ideax/tests/forms/test_idea_update.py
  ideax/tests/forms/test_use_term.py
  ideax/tests/models/__init__.py
  ideax/tests/models/test_category.py
  ideax/tests/models/test_category_image.py
  ideax/tests/models/test_criterion.py
  ideax/tests/models/test_idea.py
  ideax/tests/models/test_phase.py
  ideax/tests/test_base.py
  ideax/tests/test_mail.py
  ideax/tests/test_page_views.py
  ideax/tests/test_signals.py
  ideax/tests/views/__init__.py
  ideax/tests/views/snapshots/__init__.py
  ideax/tests/views/snapshots/snap_test_misc.py
  ideax/tests/views/test_accept_use_term.py
  ideax/tests/views/test_audit.py
  ideax/tests/views/test_idea_list.py
  ideax/tests/views/test_index.py
  ideax/tests/views/test_misc.py
  ideax/views.py
  pytest.ini
  requirements/_test.txt
Labels: enhancement

#102 Improve test coverage
  .travis.yml
  Makefile
  ideax/badwords.py
  ideax/ideax/models.py
  ideax/ideax/tests/fixtures.py
  ideax/ideax/tests/forms/snapshots/snap_test_category.py
  ideax/ideax/tests/forms/test_category.py
  ideax/ideax/tests/models/test_category.py
  ideax/ideax/tests/models/test_use_term.py
  ideax/ideax/tests/views/test_accept_use_term.py
  ideax/ideax/tests/views/test_use_term.py
  ideax/ideax/views.py
  ideax/tests/fixtures.py
  ideax/tests/test_bad_words.py
  setup.cfg
Labels: qa

#106 Fix UserProfile migrations
  docker/initialdata.json
  ideax/ideax/migrations/0023_auto_20181022_1359.py
  ideax/users/migrations/0001_initial.py
  ideax/users/models.py
Labels: bug

#105 Validate 140 chars idea summary
  ideax/ideax/forms.py
  ideax/ideax/tests/forms/test_idea.py
  ideax/ideax/tests/models/test_idea.py
Labels: bug

#108 Better sqlite support
  .travis.yml
  Readme.md
  conftest.py
  ideax/ideax/migrations/0023_auto_20181022_1359.py
  ideax/tests/fixtures.py
Labels: qa

#111 Gravatar support
  ideax/ideax/templates/ideax/base.html
  ideax/settings/_base.py
  ideax/settings/apps/_gravatar.py
  ideax/static/css/idea.theme.css
  requirements/_base.txt
Labels: enhancement

#113 WIP: Sign up
  Makefile
  conftest.py
  ideax/ideax/templates/ideax/base.html
  ideax/ideax/templates/ideax/index.html
  ideax/ideax/templates/registration/login.html
  ideax/tests/fixtures.py
  ideax/urls.py
  ideax/users/forms.py
  ideax/users/templates/users/profile.html
  ideax/users/templates/users/sign_up.html
  ideax/users/tests/fixtures.py
  ideax/users/tests/forms/__init__.py
  ideax/users/tests/forms/snapshots/__init__.py
  ideax/users/tests/forms/snapshots/snap_test_signup.py
  ideax/users/tests/forms/test_signup.py
  ideax/users/tests/models/__init__.py
  ideax/users/tests/models/test_profile.py
  ideax/users/tests/test_templates.py
  ideax/users/tests/test_urls.py
  ideax/users/tests/views/__init__.py
  ideax/users/tests/views/test_profile.py
  ideax/users/tests/views/test_signup.py
  ideax/users/urls.py
  ideax/users/views.py
  locale/en/LC_MESSAGES/django.po
  locale/pt_BR/LC_MESSAGES/django.po
Labels: enhancement

#109 dimensions CRUD #35
  ideax/ideax/forms.py
  ideax/ideax/templates/ideax/base.html
  ideax/ideax/templates/ideax/criterion_edit.html
  ideax/ideax/templates/ideax/criterion_list.html
  ideax/ideax/templates/ideax/criterion_new.html
  ideax/ideax/templates/ideax/dimension_edit.html
  ideax/ideax/templates/ideax/dimension_list.html
  ideax/ideax/templates/ideax/dimension_new.html
  ideax/ideax/templates/ideax/includes/partial_dimension_list.html
  ideax/ideax/templates/ideax/includes/partial_modal_delete.html
  ideax/ideax/tests/forms/snapshots/snap_test_dimension.py
  ideax/ideax/tests/forms/test_dimension.py
  ideax/ideax/tests/models/test_dimension.py
  ideax/ideax/tests/views/test_dimension.py
  ideax/ideax/urls.py
  ideax/ideax/views.py
  ideax/static/js/modal.js
Labels: enhancement
